server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=source, ohh
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**


