spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.75.19:3306/linksauce
    username: root
    password: 123456
  # redis 配置
  redis:
    port: 6379
    host: 192.168.88.130
    database: 0
    password: 123456
server:
  address: 0.0.0.0
linksauce:
  client:
    access-key: ohh
    secret-key: abcdefgh
dubbo:
  application:
    name: dubbo-api-platform-backend-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848